config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "trainers#index"
  resources :trainers, only: [:index, :show ]
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :trainer
  monetize :amount_cents
  validates :address, presence: true
  validates :postcode, presence: true
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  belongs_to :category
  monetize :price_cents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
      @orders = current_user.orders.where(state: 'Sent to Acquired')
  end

  def create
    random_number = rand(10_000..99_999)
    trainer = Trainer.find(params[:trainer_id])
    order = Order.create!(trainer: trainer, trainer_sku: trainer.sku, amount: trainer.price, state: 'pending', user: current_user, order_uniq: random_number, address: params[:address], postcode: params[:postcode])
    redirect_to new_order_payment_path(order)
  end
end

app/controllers/payments_controller.rb
require 'uri'
require 'net/http'
require 'JSON'

class PaymentsController < ApplicationController
  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end

  def create
    @order = current_user.orders.find(params[:order_id])

    url = URI("https://test-api.acquired.com/v1/login")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(url)
    request["accept"] = 'application/json'
    request["content-type"] = 'application/json'
    request.body = "{\"app_key\":\"b32d7ac32a22fa9eec4e6d1d79c29c7d\",\"app_id\":\"41695837\"}"

    response = http.request(request)
    body = response.read_body
    data = JSON.parse body
    access_token = data['access_token']

    payment_link_url = URI("https://test-api.acquired.com/v1/payment-links")

    http = Net::HTTP.new(payment_link_url.host, payment_link_url.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(payment_link_url)
    request["accept"] = 'application/json'
    request["content-type"] = 'application/json'
    request["authorization"] = "Bearer #{access_token}"
    request.body = {
      transaction: {
        currency: 'gbp',
        moto: false,
        capture: true,
        order_id: @order.order_uniq,
        amount: @order.amount_cents / 100
      },
      customer: {
        first_name: @order.user.first_name,
        last_name: @order.user.last_name
      },
      billing: {
        address: @order.address
      },
      shipping: {
        address_match: true,
        address: { line_1: @order.address, postcode: @order.postcode},
        email: @order.user.email
      },
      payment: {reference: @order.id.to_s },
      customer: { shipping: { address_match: false } },
      tds: { is_active: false},
      is_recurring: false,
      count_retry: 3,
      expires_in: 259200,
      payment_methods: ['pay_by_bank','google_pay', 'card', "apple_pay"],
    }.to_json
    response = http.request(request)
    body = response.read_body
    puts body
    data = JSON.parse body
    link_id = data['link_id']
    checkout_url = "https://test-pay.acquired.com/v1/#{link_id}"
    puts checkout_url
    if redirect_to checkout_url, allow_other_host: true
      puts "successfully redirected!"
      @order.state = "Sent to Acquired"
      @order.save
      puts "changed the order status"
    end
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SneakerHeads</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/orders/show.html.erb
<div class="container">
<h1> <%= current_user.first_name %>'s orders... </h1>
  <div class="row">
    <% @orders.each do |order| %>
      <div class="col-6 col-md-4">
        <div class="card m-3 shadow">
          <%= image_tag order.trainer.photo_url , height: 300, class: "card-img-top object-fit-cover" %>
          <div class="card-body">
            <h5 class="card-title"><%= order.trainer.name %></h5>
            <div class="row">
              <div class="col">
                <p class="card-text">👟 <%= order.trainer.category.name %></p>
                <p class="card-text">💳 MasterCard </p>
                <p class="card-text">🆔 <%= order.order_uniq %></p>
              </div>
              <div class="col">
                <p class="card-text">📍 <%= order.address %>, <%= order.postcode %></p>
                <p>💸 <%= humanized_money_with_symbol(order.trainer.price) %></p>
                <p class="card-text">🕒<%= order.created_at.to_date %></p>
             </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/payments/new.html.erb
<div class="container">
  <div class="row py-4 shadow m-3">
    <div class="col-md-3"><%= image_tag @order.trainer.photo_url, width: '100%' %></div>
    <div class="col position-relative">
      <div>
        <h1>Checkout summary </h1>
        <p>Purchase of <strong><%= @order.trainer.name %></strong> for <strong><%= humanized_money_with_symbol @order.amount %> 🚀</strong></p>
      </div>
      <div class="mt-2">
        <h3> Shipping Address:</h3>
        <h5> 📍<%=@order.address%>, <%= @order.postcode %> </h4>
      </div>
      <div class="position-absolute bottom-0 mt-3">
        <%= button_to 'Purchase', order_payments_path(@order), class:"btn btn-outline-primary btn-lg", method: :post%>
        <div class="d-flex gap-3">
          <p class="mt-4">You will be re-directed to a hosted checkout page powered by Acquired.com</p>
          <button class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">Who are Acquired.com?</button>
        </div>
      </div>
    </div>
  </div>
</div>

<!--ACQUIRED.com Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Acquired.com</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Acquired.com is a data-rich payments platform designed as a complete solution to fulfil all merchant’s payment requirements, from pay-in to pay-out – on a single platform.
          <br>
          <br>They are FCA regulated and can process Visa, Mastercard and American Express payments via web, mobile and virtual terminal.
          <br>
          <br>Find further details at: https://acquired.com
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "SneakerHeads 👟", trainers_path, class: "navbar-brand"%>
    <%  if user_signed_in? %>
    <h2 class="mt-2">
      <%= "Welcome #{current_user.first_name}"%>
    </h2>
    <% end %>
    <h1>
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
         <li>
            <%= link_to "Orders", order_path(1), class: "navbar-brand"%>
        </li>
        <li>
            <%= link_to "Home", trainers_path, class: "navbar-brand"%>
        </li>
        <li>
          <%= link_to "Log out", destroy_user_session_path, class: "navbar-brand", data: {turbo_method: :delete} %>
        </li>
        <% else %>
         <li>
          <%= link_to "Login", new_user_session_path, class: "navbar-brand" %>
         </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/trainers/index.html.erb
<div class="container">
  <div class="row">
    <% @trainers.each do |trainer| %>
      <div class="col-6 col-md-4">
        <div class="card m-3 shadow">
          <%= image_tag trainer.photo_url , height: 300, class: "card-img-top object-fit-cover" %>
          <div class="card-body">
            <h5 class="card-title"><%= trainer.name %></h5>
            <p class="card-text"><%= trainer.category.name %></p>
            <p>Amount: <%= humanized_money_with_symbol(trainer.price) %></p>
            <%= link_to "More details", trainer_path(trainer), class: "btn btn-outline-success" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/trainers/show.html.erb
<div class="container py-3">
  <div class="has-bg-img">
    <div class="bg-img bg-fit" style="background-image: url('<%= asset_path(@trainer.photo_url)%>')">
        <div class="content-overlay">
          <h1><%= @trainer.name %></h1>
          <p><%= @trainer.description %></p>
          <p>Amount: <%= humanized_money_with_symbol(@trainer.price) %></p>
          <h1 id="btn-target" class="btn btn-outline-success">Still keen?</h1>
          <div id="form-target" class="form-group d-none">
            <%= form_with url: orders_path do |form|%>
            <%= form.label :address, "Address:", class:"mt-3"%>
            <%= form.text_field :address, class:"form-control mt-3" %>
            <%= form.label :postcode, "Postcode:", class: "mt-3" %>
            <%= form.text_field :postcode, class:"form-control mt-3"%>
            <%= hidden_field_tag 'trainer_id', @trainer.id %>
            <%= submit_tag 'Go to checkout summary', class: 'btn btn-outline-secondary mt-3' %>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>